### ISSUE TITLE
A finished filtering event ?

### ISSUE THREAD

**Issue by Nooay** [oKcerG/SortFilterProxyModel#44]
In the sortFilterPoxyModel, it is not possible to know when these one has finished the filtering of an input list that has just been changed which for example doesn't allow the positionning of a listView on modification of the input list.

To realize that, follow these steps:
	- Modification of the input list of the sortFilterPoxyModel on user's action
	- Tracing of the input list changed event
	- Tracing of the contentHeightChanged event of the listView
	
After the input list change event, we observe that few contentHeightChanged events are thrown which means that the filtering is still running.
The problem is that we can't know when this filtering is finished which doesn't allow to perform actions successive to input list changing.

A nice solution would be to throw an event after the filtering is done.

Best regards

**Comment by oKcerG** [comment]
Hello,

I don't think that's possible.
I'm guessing the reason why you are getting multiple `contentHeightChanged` signals is because your model is sorted. So for one pair of `rowsAboutToBeInserted`/`rowsInserted` signals in the source model, the proxy model has to send multiple ones so they can be contiguous.

This behaviour is needed and is done here in Qt source code: https://github.com/qt/qtbase/blob/v5.9.1/src/corelib/itemmodels/qsortfilterproxymodel.cpp#L683-L727

From our point of view we can only know when `filterAcceptRows` is called, and not much else.

Maybe you could try with a hack where you connect to the source model `rowsInserted` signal, wait a tick of the event loop (with [`Qt.callLater`](http://doc.qt.io/qt-5/qml-qtqml-qt.html#callLater-method), or a 0 ms timer?) to make sure the inserted rows are sorted/filtered, and then run your code.

Or you could rethink your reasons why you need that. What's your usecase?
