### ISSUE TITLE
crash when appending Json array directly

### ISSUE THREAD

**Issue by rigoryan** [oKcerG/SortFilterProxyModel#46]
It seemed that when appending dict in Json array to ListModel, proxymodel crashes.
It would be great if someone can reproduce this.
I am running on windows 10, using QT 5.9.2

The testing code snippet is attached below.
if I split array and attach entry separately, everything works fine.

    ListModel {
        id: test
//        ListElement {
//            first_name: "Erwan"
//            last_name: "Castex"
//            count: 100
//            sum: 99.99
//            ssn: "xxxxxxx"
//        }
        // ...
        Component.onCompleted: {
//            test.clear()
//            test.append({first_name:"jun", last_name:"yan", count:100, sum: 888, ssn:"xxx"})
        }
    }
    SortFilterProxyModel{
        id: _proxy_model
        sourceModel: _model
        sorters: StringSorter{ roleName: "first_name"}
    }

    Timer{
        interval: 2000
        running: true
        repeat: true
        property int rand: 1
        onTriggered: {
            test.clear()
//            test.append([
//                            {first_name:"jun" +  (++rand).toString(), last_name:"yan", count:100, sum: 888, ssn:"xxx"},
//                            {first_name:"jis" +  (++rand).toString(), last_name:"yan", count:100, sum: 888, ssn:"xxx"}
//                        ])

            test.append(
                            {first_name:"jun" +  (++rand).toString(), last_name:"yan", count:100, sum: 888, ssn:"xxx"}
                        )

            test.append(
                            {first_name:"jin" +  (++rand).toString(), last_name:"yan", count:100, sum: 888, ssn:"xxx"}
                        )
        }

**Comment by rigoryan** [comment]
Maybe this is intended behavior according to doc "This means you can use it with custom c++ models or ListModel, but not with JavaScript models like arrays, integers or object instances."
Can this be confirmed?

**Comment by oKcerG** [comment]
Thank you for opening this issue.
What you are using is a `ListModel` so it's supported by this lib. If you can set it as a model it's fine.
Crashing is not intended behavior, I'll try to reproduce it and see how to fix it.

**Comment by dnvdmitry** [comment]
I can confirm that there is a crash if tou are trying to append smth to the source model. Could be reproduced with Qt 5.8, Qt 5.9 and Qt 5.10. This issue is somehow related to QSortFilterProxyModel::invalidate(); If you try to call QMetaObject::invokeMethon(this, "invalidate" Qt::QueuedConnection) the crash is fixed but there is a problem with duplicated entries inside ListView.

Here is a code snippet I'm playing with :
   ListModel {
      id : contactListModel
   }

   SortFilterProxyModel {
       id: contactListModelProxy
// workaround!!!       sourceModel: null
       sourceModel: contactListModel
       filterRoleName: "name"
       filterPattern: contactList.sortPattern
       filterCaseSensitivity: Qt.CaseInsensitive
       sortRoleName: "name"
   }
   Component.onCompleted: {
      var contactsFromSettings = appProxy.getContacts();
      for ( var idx = 0; idx < contactsFromSettings.length; idx++ ) {
         var contact = contactsFromSettings[idx];

         contactListModel.append( { "name" : String(contact["name"]),
                                    "avatar" : String(contact["avatar"])
                                  }
                                 );
      }
      // workaround !!!
      //contactListModelProxy.sourceModel = contactListModel;
      contactListView.currentIndex = -1;
   }

**Comment by oKcerG** [comment]
Yes, I reproduced the bug yesterday when appending 2 rows at once and with a sorter enabled.
I fixed the crash but it leads to another bug where the data is not correctly sorted if you don't append after. I'm still figuring out the best fix.

The problem comes from the fact that ListModel doesn't have any role at start, and doesn't emit a signal to tell it got new roles.

(btw: note that using `filter`/`sortRoleName` and friends is deprected. It's still supported though but you might want to switch to `filters` and `sorters`)
